kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bm-dev-clusters-hpe-redhat
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: hpe_redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:managedclusterset:admin:bm-dev-clusters'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpe-redhat-rb-applications
  namespace: openshift-gitops
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: hpe_redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: applications.app.k8s.io-v1beta1-edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpe-redhat-rb-applications-argocd
  namespace: openshift-gitops
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: hpe_redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: applications.argoproj.io-v1alpha1-edit
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-cluster-credentials
  namespace: open-cluster-management
rules:
  - verbs:
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - secrets
      - namespace
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - vcenter
      - baremetal
      - hostinventory
